{% set version = "1.0" %}

package:
  name: gridutils
  version: {{ version }}

source:
  url: https://github.com/sakov/gridutils-c/archive/v{{ version }}.tar.gz
  sha256: ec304157ea05e520dfa07dd13f72534c5df06081

build:
  number: 3
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - nn
    - csa
  run:
    - nn
    - csa

test:
  commands:
    - gridbathy -h
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: https://github.com/sakov/gridutils-c
  license: BSD 2-Clause
  license_file: gridutils/LICENSE
  summary: 'C library functions and command line utilities for working with curvilinear grids.'

extra:
  recipe-maintainers:
    - ocefpaf
