# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: beta-xcode6.1

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "exQquvz4VsG5g4r672xxsa3VfqyKlwkEs9VHUWvbCmGWa3HTnHtJNH18F0KbBOmkj7tdETO5Jbz+FK24Jr875sv7QZmfdtAZ8WI9TgRttGFzli8Vus6Er2F08pQd1wnDfdYt6AYNd+WDnPx7I1aFQh8pzibc17QZUdFsGmX1l3GpAzmtntGew/0FPjYNQOpFTtKY92SWsuvXYnxkuLB35pVZsl7EoAKfZdbBgEYKZ+p5zP+xVB0dZ7C1zeLDquG/nxC5wL/FEJu9kZrk49QvdsyTRUoe2vxwC60ACcmdQtRulJh7KBXF/Qx9t8J2YpYFXmBKcu30gAd9sJeBJtYoY4uEx9lQq5tZujso0blY8yG3hgcak6TmuFXivwa6CVbAz8lulqQImBdEzSpmZNv9IWp7qjZ2jKE02CqbX/xYDtK3stQfP9rFopkh5H6Nq1GqXXoUwJ5+OZwUlWIo6EdQJbnApmxDx8DldkL3TP8YdBRXCCwxHpM7NxqsTfwelJKwU5WsgEvYN+RjejXBsruFB6CrtN+osSW72NUh+K73xt+fG16z0UGY4y4ZVrrwtHJr+mB3uPrpuh2Mhhbg7W22AsLVpV6Itl94+DtIxHM2rgz9x8W/ipiRy+1U8NJVdRIWwwS1ILZAsREsi9NfbwLPatgnpCyPGkYMQauOWct+1cM="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
