appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: vWFabdTVgj3cNb3J6GewmvLcqShhxyiuyjKEdfN20C03CQml2CgA/GKC7A76E9AZ0ZJ7GNP4rTrEuvKE9SqehLlnDqlcEm6ARVVoXgYrAEqbCYKPfdDKljfOsANZRP9sBdltJOkTuQlTByyn6OwL+DlkJRSDP/WckQEONoWee7YTdWP0gcJJWW3p+TdzWgGrkxWiA+XqBIrZBNCEDDyM9P2b0mrCGMMAH9lzGJCn3hZOhrxij3xUTE1tt03maW05MM2psd6VlpY1nq5q0dkw6XFtjKSixLjajdbqpDbEuNpwHZiDdmTiaTGzD4mHGZ7w63oYEvNNRFtp7fh5dffho91uDXV8f1QmgFHiAh7ras784ehG1NurpjY749kdvpVMgDVhcUCiWIvlolrHrquq8DNkA9MECEnbFdbsZu8mSdGgy4IOYKSl5Ch2HRP7SmUE+Xkkdyr1QhRNU32IGlPBfwTMNMwoGJKElS7ShdAVvU6g3FRjbs37rqiKzkOmCE9fW6b2CzC/Uf5VUJYxpND+tTfid49+NmvnDLTumf0PvgFJlVCfDOPLN+e08EYqmAmV9egWaXlRAbc7xRf+Sjn2PEhmwm+WoMBdSUGsrrUHi4h17AE5KLbm54SsgyjIi/gLwf1a6Gaf2huHyT2oCqjz2sty67Vp+Zsw/ILamSX+Izg=}
conda_forge_output_validation: true
