travis:
  secure:
    BINSTAR_TOKEN: GR3k0yLTXp0orxuNEYLc9QwFdzO+0KHcKOiwkiC15jSMfEZiDq4dplb1eEnCCC1XkxtJVmcLY5nW14EYzH8nuP+LPgODihvv3IuhOQoEsw7REjamK/LtWOh0bJ6rZ81X2ioPELNe/MWx65LwsePNf0eAqZ2MWVQjloS+M6L/W8nRYd7BANIQYUgbYodFzNIsGi+i2KQotsVtgknaMGrCPofnlO3OBDg6LTo9vxY7Xq/L3c2Vt6E090jmM5dS9fWkP/hJ1rl2MzVOsGBrZO0dnGvpdjRHlqFRy6jWd0Dx0QXUFv7hKyutjxHyoOR+javnSKvv7ZFhVMDv5etm1qeHItXNx89bsslnpRkb8D7+SyYJyPZ/KsTmhRiMZaNuFss892Kf9VVisvgSk27CK08lHfpyB5UQs2r6PDZwjCWR0hgw4bibwtpFvNOxeHG3rv73d3+dQZ/h9JUScz0Gs3hDQBaOI8S9Kz5BREgZTSfCaLaehP8ZzoZymqh0I94ozJJ74oMhMlH7maLuoRGeGGogxJ6+mKxLv8ltrUxTFP9MNpYAaG2pkOkb1bgZfUIWhpVwQXAubuTemqs1JwTpStTCeP+RilPGqi0GyXNK1Bd80Qr/YIUNJeZHpEFwu84xXME8tra5yeHkw800TeMhw1u5LQWtYDrDOLHOD/TBFdZQA+o=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
